export const options = [
  { value: '64', label: 'Liverpool FC' },
  { value: '65', label: 'Manchester City FC' },
  { value: '73', label: 'Tottenham Hotspur FC' },
  { value: '61', label: 'Chelsea FC' },
  // { value: '73', label: 'Tottenham Hotspur FC' },
  // { value: '73', label: 'Tottenham Hotspur FC' },
  // { value: '73', label: 'Tottenham Hotspur FC' },
  // { value: '73', label: 'Tottenham Hotspur FC' },
  // { value: '73', label: 'Tottenham Hotspur FC' },
  // { value: '73', label: 'Tottenham Hotspur FC' },
  // { value: '73', label: 'Tottenham Hotspur FC' },
  // { value: '73', label: 'Tottenham Hotspur FC' },
  // { value: '73', label: 'Tottenham Hotspur FC' },
  // { value: '73', label: 'Tottenham Hotspur FC' },
  // { value: '73', label: 'Tottenham Hotspur FC' },
  // { value: '73', label: 'Tottenham Hotspur FC' },
  // { value: '73', label: 'Tottenham Hotspur FC' },
  // { value: '73', label: 'Tottenham Hotspur FC' },
  // { value: '73', label: 'Tottenham Hotspur FC' },
  { value: 'vanilla', label: 'Vanilla' }
]
